# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=10)),
                ('OwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carz', to='authentication_app.User')),
            ],
        ),
    ]
