# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='OwnerId',
            field=models.IntegerField(default=0),
        ),
    ]
