# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_remove_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserName',
        ),
    ]
